### ISSUE TITLE
Codepen example breaks with latest vugel

### ISSUE THREAD

**Issue by husayt** [Planning-nl/vugel#4]
If you try any vugel version >= 1.0.13, Codepen [example](https://codepen.io/basvanmeurs/pen/vYNGRGP?editors=1010) mentioned in readme gets broken

**Comment by RobbinBaauw** [comment]
Good catch! https://github.com/Planning-nl/vugel/commit/faa068fb08f2e4b3fe8ec62fab282f4b68fb19bd#diff-e0996ff8a423b594eb5ad38891f650a8L17 has broken it, because the runtime is passed to the render function this may actually be required. I think we should actually pass a combination. For now you can use https://pastebin.com/raw/mpL94HkF if you want to use it with the codepen
